name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: SSH into LUNA
      uses: appleboy/ssh-action@master
      with:
        host: 45.77.6.116 
        username: root
        key: ${{ secrets.PRIV_KEY }}
        port: 19122
        script: |
          cd WaluigiBot
          git pull origin master
          git status
          echo ${{ secrets.PRIV_KEY }} > priv_key.txt
          echo ${{ secrets.TOKEN }} > WahToken.txt
          docker-compose up -d --build
